#!/bin/python3

import math
import os
import random
import re
import sys
# Complete the cutTheSticks function below.
def cutTheSticks(sticks):
    arr.sort(reverse=True)
    a=[]
    while len(arr) > 0:
        a.append(len(arr))
        m=min(arr)
        for i in arr:
            i=i-m
        last= arr.pop()
        while len(arr) > 0 and last in arr:
            arr.pop()
    return(a)


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    arr = list(map(int, input().rstrip().split()))

    result = cutTheSticks(arr)

    fptr.write('\n'.join(map(str, result)))
    fptr.write('\n')

    fptr.close()

