#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the permutationEquation function below.
def permutationEquation(p):
    n1=[]
    n2=[]
    for x in range(1,n+1):
        if x in p:
            n1.append((p.index(x))+1)
    for i in n1:
        if i in p:
            n2.append((p.index(i))+1)
    return(n2)

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    p = list(map(int, input().rstrip().split()))

    result = permutationEquation(p)

    fptr.write('\n'.join(map(str, result)))
    fptr.write('\n')

    fptr.close()

